import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import second from "../../public/second.jpg";
import frontend from "../../public/frontend.jpg";
import backend from "../../public/backend.jpg";
import AI from "../../public/AI2.jpg";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.png";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";
import web6 from "../../public/web6.png";
import React from "react";

import { useState } from "react";
import useDownloader from "react-use-downloader";

const fileUrl = "/AmehSolomonOnyekeResume.pdf";
const fileName = "Ameh Solomon Onyeke";

export default function Home() {
  const { download } = useDownloader();
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ameh Solomon Onyeke</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-2xl font-burtons">A.S.O</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  onClick={() => download(fileUrl, fileName)}
                >
                  Resume
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-5xl">
              Ameh Solomon Onyeke
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Fullstack Web Developer and AI Enthusiast
            </h3>
            <p className="text-md py-5 leading-8 text-gray-700 dark:text-gray-200 md:text-lg max-w-lg mx-auto ">
              A tech bro with a wide range of skills and services to offer. You
              can reach me through any of the provided platforms.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              target="_blank"
              rel="noreferrer"
              href="https://twitter.com/uncle_solomon"
            >
              <AiFillTwitterCircle />
            </a>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://github.com/Uncle-Solomon"
            >
              <AiFillGithub />
            </a>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.linkedin.com/in/ameh-solomon-onyeke-a69874162/"
            >
              <AiFillLinkedin />
            </a>
            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.instagram.com/uncle_soyo/"
            >
              <AiFillInstagram />
            </a>
          </div>
          <div className="relative rounded-full w-60 h-60 mt-10 mx-auto overflow-hidden pb-10 md:h-96 md: mb-10 md:w-96">
            <Image src={second} fill />
          </div>
        </section>
        {/* Another Section */}

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200">
              I focus majorly on{" "}
              <span className="text-teal-500"> backend technology </span> but I
              still know a little about{" "}
              <span className="text-teal-500"> frontend </span> :|. I also
              dabble in a bit of{" "}
              <span className="text-teal-500">AI, Machine Learning</span> and{" "}
              <span className="text-teal-500">Embedded Systems </span>. I am
              currently learning more frameworks and developing my skillset - I
              regularly document my learning progress on Github.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ">
              <Image
                src={frontend}
                className="mx-auto"
                width={150}
                height={150}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">FrontEnd</h3>
              <p className="py-2">
                Bringing expert user interface and experience designs to life
                with the use of recent frontend frameworks and packages.
              </p>
              <h4 className="py-4 text-teal-600">Tools and Frameworks I use</h4>
              <p className="text-gray-700 py-1">ReactJS</p>
              <p className="text-gray-700 py-1">JavaScript</p>
              <p className="text-gray-700 py-1">HTML</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={backend}
                className="mx-auto"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Backend</h3>
              <p className="py-2">
                Developing architecture that would support your application;
                Integrating APIs, Databases and Authentication.
              </p>
              <h4 className="py-4 text-teal-600">Tools and Frameworks I use</h4>
              <p className="text-gray-700 py-1">NodeJs</p>
              <p className="text-gray-700 py-1">Python Flask</p>
              <p className="text-gray-700 py-1">MongoDB | PostgreSQL</p>
              <p className="text-gray-700 py-1">PostMan</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={AI} className="mx-auto" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                AI / Machine Learning
              </h3>
              <p className="py-2">
                Creating models and exploring solutions that can be deployed
                through the use fo machine learning techniques.
              </p>
              <h4 className="py-4 text-teal-600">Tools and Frameworks I use</h4>
              <p className="text-gray-700 py-1">Jupyter Notebook</p>
              <p className="text-gray-700 py-1">Python</p>
              <p className="text-gray-700 py-1">Scikit Learn</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-200">
              The section that follows highlights a few of my recently completed
              projects.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                alt=""
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
